### ISSUE TITLE
questions on SEV LTER plots: Moore23 Plots

### ISSUE THREAD

**Issue by lizzieinvancouver** [JulieSieg/Soil-Moisture#2]
Okay, so my take home from these plots is that the Moore23 data is of lower quality (more gaps?) than the Gosz16 Plots?

**Comment by JulieSieg** [comment]
Yes, 90% of the hourly data is NA for Moore23 so its not very reliable. There wasn't much consistency in the time of year there was good data either.

**Comment by lizzieinvancouver** [comment]
@JulieSieg thanks for explaining! Seems like not useful data really so we can stop working on it.
