### ISSUE TITLE
questions on LTER in Colorado: Andrus22 Plots

### ISSUE THREAD

**Issue by lizzieinvancouver** [JulieSieg/Soil-Moisture#3]
@JulieSieg These plots are great! Which LTER is it? Even though it wasn't the goal I am intrigued to see the difference between this and SEV. 

Do you know why some of the data has negative soil moisture reported? Do they explain that in the metadata or such?

**Comment by JulieSieg** [comment]
@lizzieinvancouver this is from the Niwot Ridge LTER in Colorado. 

The metadata says this about the negative values: "The soil moisture values were not calibrated and in some cases the data may only be appropriate for interpreting relative soil moisture changes over time (e.g., negative values)."

**Comment by lizzieinvancouver** [comment]
@JulieSieg Wow! That's crazy that they did not regularly calibrate it (though I can sort of understand). I think it means we cannot really compared this site to other sites easily. 

If any other sites mention that, please flag it somewhere and tell me.
